version: '3.3'

services:
  app:
    build:
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    command: npm start
    volumes:
      - .:/app
  
  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./services/caddy/Caddyfiles:/etc/caddy/Caddyfile
    depends_on:
      - app
