version: '3.3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    command: ["npm", "test"]
    depends_on:
      - db
  db:
    image: postgres:latest
    env_file: env.example
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
   
