version: '3.3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.producton
    command: ["npm", "test"]
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${NODOS_DB_HOSTNAME}
      POSTGRES_USER: ${NODOS_DB_USERNAME}
      POSTGRES_PASSWORD: ${NODOS_DB_PASSWORD} 
   
